[build]
command = "corepack enable && pnpm build"
publish = "dist/sangue-real-site/browser"

[build.environment]
NODE_VERSION = "22"
NETLIFY_USE_PNPM = "true"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
